### ISSUE TITLE
Deploy the app

### ISSUE THREAD

**Issue by Hagryn** [HE-Arc/Vacances#10]

**Comment by Ozurah** [comment]
étape requirements : ebe66192745f1e427c7ea6029d9ebc9f2b714d93
.env support : cd57ad1d75d26d26060fc259a5a12b7abc4115bc 798cf7219c1e121426757c3f93cc537366499537

**Comment by Ozurah** [comment]
Déploiement effectué, ce qui a été réalisé est disponible sur le wiki https://github.com/HE-Arc/Vacances/wiki/Deploiement-serveur
